# Generated by Django 5.1.5 on 2026-06-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0003_assessment_assessmentanswer_prediction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentanswer',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
