# Generated by Django 5.1.5 on 2026-06-21 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0004_assessmentanswer_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('academic_year', models.IntegerField(default=1)),
                ('cgpa', models.FloatField(default=0)),
                ('course', models.CharField(default='', max_length=100)),
                ('residence_type', models.CharField(default='', max_length=100)),
                ('internet_usage', models.FloatField(default=0)),
                ('daily_steps', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
