# Generated by Django 5.1.5 on 2026-06-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0006_dashboardresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='family_expectation',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='financial_stress',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='physical_activity',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='screen_time',
            field=models.FloatField(default=4),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sleep_hours',
            field=models.FloatField(default=7),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_support',
            field=models.IntegerField(default=3),
        ),
    ]
