# Generated by Django 5.1.5 on 2026-06-22 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0007_userprofile_family_expectation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assessmentanswer',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mental_health.assessment'),
        ),
        migrations.AlterField(
            model_name='dashboardresult',
            name='recommendations',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dashboardresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='sleep_hours',
            field=models.FloatField(default=7),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='mental_health.assessment'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='mental_health.assessment'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='primary_goal',
            field=models.CharField(default='Improve Mental Wellness', max_length=100),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
