# Generated by Django 5.1.5 on 2026-06-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental_health', '0009_assessmentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentreport',
            name='recommended_activities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='assessmentreport',
            name='recommended_music',
            field=models.JSONField(default=list),
        ),
    ]
